// <auto-generated />
using System;
using KhuddarVSDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KhuddarVSDatabase.Migrations
{
    [DbContext(typeof(KhuddarContext))]
    [Migration("20200901090043_servicesitems")]
    partial class servicesitems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("article")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("articleType")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("videoLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KhuddarArticles");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarCofinGrantServices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("KhuddarCofinGrantServices");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarCofinGrantedServicesItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<int>("quanity")
                        .HasColumnType("int");

                    b.Property<int>("serviceId")
                        .HasColumnType("int");

                    b.Property<int>("serviceItemId")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("serviceId");

                    b.HasIndex("serviceItemId");

                    b.ToTable("KhuddarCofinGrantedServicesItems");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarCofinRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<string>("patientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<int?>("userId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("KhuddarCofinRequest");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarEarnToPLayVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("expiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<string>("thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("videoId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KhuddarEarnToPLayVideos");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarQuiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<int?>("Category")
                        .HasColumnType("int");

                    b.Property<int>("CorrectAnswer")
                        .HasColumnType("int");

                    b.Property<bool>("HasVideo")
                        .HasColumnType("bit");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<string>("VideoLink")
                        .HasColumnType("varchar(MAX)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("KhuddarQuizs");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarQuizAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuizQuestion")
                        .HasColumnType("int");

                    b.Property<int>("ansStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("QuizQuestion");

                    b.ToTable("KhuddarQuizAnswers");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarQuizCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KhuddarQuizCategorys");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarQuizCompleted", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("completionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<bool?>("hasCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<int?>("userId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("KhuddarQuizCompleteds");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KhuddarRoles");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarServices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KhuddarServices");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarServicesItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<string>("serviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<decimal>("unitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("KhuddarServicesItems");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarShadiMubarakUnlockMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ServiceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<int>("unlockMonth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KhuddarShadiMubarakUnlockModes");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Long")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("KhuddarUsers");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarUserDepoist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Particluer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WalletId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<string>("payemtnMethode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("KhuddarUserDepoists");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarUserGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Particluer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WalletId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("KhuddarUserGrants");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarUserLogRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Particluer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("KhuddarUserLogRecords");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarUserWallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ammount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("lastWithdraw")
                        .HasColumnType("datetime2");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<int?>("walletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("walletId");

                    b.ToTable("KhuddarUserWallet");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarWalletType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MinimumWithDrawDate")
                        .HasColumnType("int");

                    b.Property<decimal>("WalletWithdrawMinimumAmmount")
                        .HasColumnType("money");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KhuddarWalletType");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.ShadiMubarakServices.KhuddarAlNikkahServicesItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("money");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<string>("serviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KhuddarAlNikkahServicesItems");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.ShadiMubarakServices.KhuddarBaraatServicesItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("money");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<string>("serviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KhuddarBaraatServicesItems");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.ShadiMubarakServices.KhuddarFoodandFoodServicesItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("money");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<string>("serviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KhuddarFoodandFoodServicesItem");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.ShadiMubarakServices.KhuddarFurnitureServicesItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("money");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<string>("serviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KhuddarFurnitureServicesItem");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.ShadiMubarakServices.KhuddarGroomSalonServicesItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("money");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<string>("serviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KhuddarGroomSalonServicesItem");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.ShadiMubarakServices.KhuddarMarrigeBanquetServicesItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("money");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<string>("serviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KhuddarMarrigeBanquetServicesItem");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.ShadiMubarakServices.KhuddarRentAHappyCarServicesItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("money");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<string>("serviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KhuddarRentAHappyCarServicesItem");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.ShadiMubarakServices.KhuddarValimaServicesItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("money");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("deleteStatus")
                        .HasColumnType("bit");

                    b.Property<string>("serviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KhuddarValimaServicesItem");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarCofinGrantServices", b =>
                {
                    b.HasOne("KhuddarVsModals.Models.KhuddarUser", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarCofinGrantedServicesItems", b =>
                {
                    b.HasOne("KhuddarVsModals.Models.KhuddarCofinGrantServices", "KhuddarCofinGrantServices")
                        .WithMany("KhuddarCofinGrantedServicesItems")
                        .HasForeignKey("serviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KhuddarVsModals.Models.KhuddarServicesItems", "KhuddarServicesItems")
                        .WithMany()
                        .HasForeignKey("serviceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarCofinRequest", b =>
                {
                    b.HasOne("KhuddarVsModals.Models.KhuddarUser", "user")
                        .WithMany("CoffinRequest")
                        .HasForeignKey("userId");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarQuiz", b =>
                {
                    b.HasOne("KhuddarVsModals.Models.KhuddarQuizCategory", "KhuddarQuizCategory")
                        .WithMany("KhuddarQuiz")
                        .HasForeignKey("Category");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarQuizAnswer", b =>
                {
                    b.HasOne("KhuddarVsModals.Models.KhuddarQuiz", "KhuddarQuiz")
                        .WithMany("KhuddarQuizAnswers")
                        .HasForeignKey("QuizQuestion");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarQuizCompleted", b =>
                {
                    b.HasOne("KhuddarVsModals.Models.KhuddarUser", "KhuddarUser")
                        .WithMany("QuizCompletedRecords")
                        .HasForeignKey("userId");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarServicesItems", b =>
                {
                    b.HasOne("KhuddarVsModals.Models.KhuddarServices", "Service")
                        .WithMany("ServiceTypes")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarUser", b =>
                {
                    b.HasOne("KhuddarVsModals.Models.KhuddarRole", "Roles")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarUserDepoist", b =>
                {
                    b.HasOne("KhuddarVsModals.Models.KhuddarUserWallet", "Wallet")
                        .WithMany("DepositMoney")
                        .HasForeignKey("WalletId");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarUserGrant", b =>
                {
                    b.HasOne("KhuddarVsModals.Models.KhuddarUserWallet", "Wallet")
                        .WithMany("GrantedMoney")
                        .HasForeignKey("WalletId");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarUserLogRecord", b =>
                {
                    b.HasOne("KhuddarVsModals.Models.KhuddarUser", "User")
                        .WithMany("LogReport")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("KhuddarVsModals.Models.KhuddarUserWallet", b =>
                {
                    b.HasOne("KhuddarVsModals.Models.KhuddarWalletType", "WalletType")
                        .WithMany()
                        .HasForeignKey("walletId");
                });
#pragma warning restore 612, 618
        }
    }
}
